Implement molecular features for CG graphs
ur-whitelab/hoomd-tf pull request #249
Opened 2020-09-24 17:47 UTC by geemi725

2020-09-24 17:47 UTC, pep8speaks commented
Hello @geemi725! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`htf/utils.py`](https://github.com/ur-whitelab/hoomd-tf/blob/686498068c70e7388195e95b1837bd4f62d930dd/htf/utils.py):

> [Line 258:25](https://github.com/ur-whitelab/hoomd-tf/blob/686498068c70e7388195e95b1837bd4f62d930dd/htf/utils.py#L258): [E741](https://duckduckgo.com/?q=pep8%20E741) ambiguous variable name 'l'
> [Line 259:28](https://github.com/ur-whitelab/hoomd-tf/blob/686498068c70e7388195e95b1837bd4f62d930dd/htf/utils.py#L259): [E741](https://duckduckgo.com/?q=pep8%20E741) ambiguous variable name 'l'
> [Line 261:30](https://github.com/ur-whitelab/hoomd-tf/blob/686498068c70e7388195e95b1837bd4f62d930dd/htf/utils.py#L261): [E741](https://duckduckgo.com/?q=pep8%20E741) ambiguous variable name 'l'
> [Line 263:30](https://github.com/ur-whitelab/hoomd-tf/blob/686498068c70e7388195e95b1837bd4f62d930dd/htf/utils.py#L263): [E741](https://duckduckgo.com/?q=pep8%20E741) ambiguous variable name 'l'

2020-09-24 17:56 UTC, hgandhi2411 requested changes

2020-09-24 17:56 UTC, hgandhi2411 commented on htf/utils.py
> +        from numpy import asarray
os and numpy are already imported in the file

2020-09-24 17:56 UTC, hgandhi2411 commented on htf/utils.py
> +class generate_cg_graph():
Can you add documentation for this class?

2020-09-24 17:56 UTC, hgandhi2411 commented on htf/utils.py
> +        import MDAnalysis as mda
move the imports to the class. Class imports may have to be used like this: https://stackoverflow.com/a/38087292

2020-09-24 18:04 UTC, geemi725 commented on htf/utils.py
> +        import MDAnalysis as mda
Moved

2020-09-30 19:02 UTC, whitead commented on htf/utils.py
> +class generate_cg_graph():
Classes should be defined like:

`class GenerateCGGraphs`

And you should use nouns, not verbs for class names.

2020-10-01 14:13 UTC, hgandhi2411 commented on htf/utils.py
> +                                    ag += ah
@geemi725 you either need to have `else` for `if..elif` or use multiple `if` statements instead.

2020-10-01 14:15 UTC, hgandhi2411 commented on htf/utils.py
> +                    return rs, angs, dihs
Same thing here.

2020-10-01 14:29 UTC, hgandhi2411 commented on htf/utils.py
> +            "MDAnalysis and NetworkX not available")
`skiptest()` is a method of the unittest module. It throws an error here since `self.skiptest` is not defined.

2020-10-01 20:18 UTC, hgandhi2411 commented on htf/utils.py
> +            rs = np.asarray(dist_list).squeeze(axis=(1,))
Variable names should be descriptive, it is annoying to keep going back to find out what the variables are doing (for example n or r or s don't say anything about what this variable is)

2020-10-01 20:32 UTC, hgandhi2411 commented on htf/utils.py
> +        if filelist[i].endswith('.json'):
Why do you take in a filelist? I thought you only need one file with the CG mapping. Is it because you add the hydrogens back in?

2020-10-01 20:34 UTC, hgandhi2411 commented on htf/utils.py
> +    ''' Given a CG mapping in JSON format(from DSGPM model), outputs indices of connected CG beads
Is it required that one use the DPSGM model for mapping? That may be true for our group but I think we should specify the file format that we expect in the documentation instead.

2020-10-01 20:36 UTC, geemi725 commented on htf/utils.py
> +    ''' Given a CG mapping in JSON format(from DSGPM model), outputs indices of connected CG beads
this code only considers mappings in JSON format. If one wishes to use another format I have added the scripts under DSGPM github repo to convert from JSON to other mappings.

2020-10-01 20:37 UTC, geemi725 commented on htf/utils.py
> +        if filelist[i].endswith('.json'):
Because there can be instances when you have multiple mappings per molecule. I encounter them often in  my work.

2020-10-01 20:40 UTC, hgandhi2411 reviewed
Looks good! There are some stylistic changes that would be nice, I have commented those here.

2020-10-01 20:42 UTC, hgandhi2411 commented on htf/utils.py
> +        if filelist[i].endswith('.json'):
Ok great. Can you please mention in the docs that filelist is a list of different mappings. I don't have much experience of dealing with mappings.

2020-10-01 20:45 UTC, hgandhi2411 commented on htf/utils.py
> +    ''' Given a CG mapping in JSON format(from DSGPM model), outputs indices of connected CG beads
I get that., What I meant was, if someone uses their own mapping instead of using DPSGM, how should the json file be edited to be input to this function. Having an example somewhere in the docs will help people outside our group understand it better.

2020-10-02 15:32 UTC, whitead commented
@geemi725 This looks like a ton of work, nice job! Could you make sure to address those pep8 comments above about the if conditions? That's an important habit to get into.

2020-10-05 18:16 UTC, geemi725 commented
Pep8 issues addressed, variable names are changed, all tests pass. Ready for review! @hgandhi2411

2020-10-06 14:20 UTC, hgandhi2411 approved these changes
Great work @geemi725! 
I would have liked some documentation about the format of mappings but that can be a separate issue, I guess.

2020-10-06 14:28 UTC, merged