Universe sub-system is defined based on atom group selection in iter_from_traj
ur-whitelab/hoomd-tf pull request #255
Opened 2020-10-31 04:14 UTC by mehradans92

- Updated iter_from_traj func
- Updated unittest test_iter_from_traj
- Added traj and tpr files for test

2020-10-31 04:14 UTC, pep8speaks commented
Hello @mehradans92! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`htf/test-py/test_utils.py`](https://github.com/ur-whitelab/hoomd-tf/blob/d7784d9c4caa2a2597e1edf37e2b49a0c4cd5bff/htf/test-py/test_utils.py):

> [Line 415:101](https://github.com/ur-whitelab/hoomd-tf/blob/d7784d9c4caa2a2597e1edf37e2b49a0c4cd5bff/htf/test-py/test_utils.py#L415): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (104 > 100 characters)

* In the file [`htf/utils.py`](https://github.com/ur-whitelab/hoomd-tf/blob/d7784d9c4caa2a2597e1edf37e2b49a0c4cd5bff/htf/utils.py):

> [Line 428:46](https://github.com/ur-whitelab/hoomd-tf/blob/d7784d9c4caa2a2597e1edf37e2b49a0c4cd5bff/htf/utils.py#L428): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 441:1](https://github.com/ur-whitelab/hoomd-tf/blob/d7784d9c4caa2a2597e1edf37e2b49a0c4cd5bff/htf/utils.py#L441): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2020-11-09 16:24 UTC, hgandhi2411 requested changes
This great @mehradans92! Thanks for doing it. 
I have 2 stylistic comments, can you address those? I'll approve once you do it.

2020-11-09 18:17 UTC, mehradans92 commented on htf/utils.py
> +        from MDAnalysis.analysis.base import AnalysisFromFunction
The reason I used import in the if statement is that for selection='all', there is no need to redefine the universe. So this part of the code doesn't run and therefore no need to import something when it's not going to be used.

2020-11-09 18:20 UTC, hgandhi2411 approved these changes

2020-11-09 18:22 UTC, merged