Find molecules from traj
ur-whitelab/hoomd-tf pull request #269
Opened 2021-02-04 16:02 UTC by mehradans92

2021-02-04 16:02 UTC, pep8speaks commented
Hello @mehradans92! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`htf/utils.py`](https://github.com/ur-whitelab/hoomd-tf/blob/a1ce7005f7de8b282babec0b78445028259fd254/htf/utils.py):

> [Line 210:101](https://github.com/ur-whitelab/hoomd-tf/blob/a1ce7005f7de8b282babec0b78445028259fd254/htf/utils.py#L210): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (152 > 100 characters)
> [Line 216:101](https://github.com/ur-whitelab/hoomd-tf/blob/a1ce7005f7de8b282babec0b78445028259fd254/htf/utils.py#L216): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (102 > 100 characters)
> [Line 219:1](https://github.com/ur-whitelab/hoomd-tf/blob/a1ce7005f7de8b282babec0b78445028259fd254/htf/utils.py#L219): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 249:101](https://github.com/ur-whitelab/hoomd-tf/blob/a1ce7005f7de8b282babec0b78445028259fd254/htf/utils.py#L249): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (139 > 100 characters)
> [Line 252:1](https://github.com/ur-whitelab/hoomd-tf/blob/a1ce7005f7de8b282babec0b78445028259fd254/htf/utils.py#L252): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

2021-02-04 16:13 UTC, hgandhi2411 commented
@mehradans92 seems like you are importing `MDAnalysis` in utils.py. Can you only import it in your functions, since it's an optional dependency? 
Since we are using mdanalysis for so many functions, it might make sense to make it a depedency?

2021-02-04 16:16 UTC, whitead commented
We would need to modify our compilation instructions (or maybe makefile alone?) to do it. Let's just keep them in functions if possible.

2021-02-04 16:27 UTC, mehradans92 commented on htf/simmodel.py
> +    # Note that this function is compatible with HOOMD box and not the one from GROMACS.
@hgandhi2411 You might have solved this problem in your PR.

2021-02-04 16:40 UTC, hgandhi2411 commented on htf/simmodel.py
> +    # Note that this function is compatible with HOOMD box and not the one from GROMACS.
I changed the box description in `iter_from_trajectory`. Tests passed and Rainier tested it with his gsd file. Can you pull from master and test it with your GROMACS trajectory? Thanks!

2021-02-04 17:00 UTC, mehradans92 commented on htf/simmodel.py
> +    # Note that this function is compatible with HOOMD box and not the one from GROMACS.
Already done in `test_iter_from_trajectory`.

2021-02-04 17:41 UTC, hgandhi2411 requested changes

2021-02-04 17:41 UTC, hgandhi2411 commented on htf/simmodel.py
> +    # Note that this function is compatible with HOOMD box and not the one from GROMACS.
Can you remove this comment if the issue is resolved? Thanks.

2021-02-04 17:41 UTC, hgandhi2411 commented on htf/utils.py
> +    for i, ts in enumerate(tqdm(universe.trajectory)):
Good idea to see the progress here, useful for bigger universes!

2021-02-04 17:41 UTC, hgandhi2411 commented on sphinx-docs/source/changelog.rst
> +- Can read molecules from GROAMCS topology
Should this be a bug fix? Since `iter_from_traj` was originally intended to read traj files from any software that MDanalysis can handle.

2021-02-04 17:41 UTC, hgandhi2411 commented on htf/utils.py
> +                return num_index
Seems like this code is same as `find_cgnode_id()`, did you mean to use that function here? I don't see `cg` defined in this function.

2021-02-04 17:41 UTC, hgandhi2411 commented on htf/utils.py
> +    Depnding on the size of your system, this fuction might be slow to run.
typo in `Depending`

2021-02-04 17:41 UTC, hgandhi2411 commented on htf/utils.py
> +    Total_number_of_atoms = universe.select_atoms(selection).n_atoms
Can you use lowercase t? Sorry but it's to maintain consistency in code style

2021-02-04 22:38 UTC, mehradans92 commented on sphinx-docs/source/changelog.rst
> +- Can read molecules from GROAMCS topology
This is about `find_molecules_from_topology` function.

2021-02-04 22:42 UTC, mehradans92 commented on htf/utils.py
> +                return num_index
Good catch! I think this got added by accident while resolving merge conflicts. I am surprised `test_matrix_mapping` passed with this.

2021-02-04 22:49 UTC, mehradans92 commented on htf/utils.py
> +                return num_index
I see why it passed. It was defined twice!

2021-02-05 15:41 UTC, hgandhi2411 commented on htf/utils.py
> +def matrix_mapping(molecule, beads_mapping):
Is beads_mapping equivalent to mapping operator?

2021-02-05 15:54 UTC, hgandhi2411 reviewed
Looks good to me. There are still a few pep8 issues, I'll approve this PR once they are solved.

2021-02-05 15:59 UTC, mehradans92 commented on htf/utils.py
> +def matrix_mapping(molecule, beads_mapping):
Yes. I'll fix that.

2021-02-05 16:54 UTC, hgandhi2411 approved these changes

2021-02-05 17:00 UTC, merged