Mapping matrix function outputs mass and no-mass weighted mapping matrices
ur-whitelab/hoomd-tf pull request #271
Opened 2021-02-05 06:17 UTC by geemi725

Addresses issue #267

2021-02-05 06:26 UTC, pep8speaks commented
Hello @geemi725! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`htf/utils.py`](https://github.com/ur-whitelab/hoomd-tf/blob/9afe9361946cc5a63ab67f3a6a5b520bef9ab0c2/htf/utils.py):

> [Line 516:17](https://github.com/ur-whitelab/hoomd-tf/blob/9afe9361946cc5a63ab67f3a6a5b520bef9ab0c2/htf/utils.py#L516): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'

2021-02-05 15:27 UTC, mehradans92 reviewed
the variable `matrices` is kinda vague, so you might want to use a different one. Also, maybe you just want to make one output for the function based on user's choice for  `matrices` option.

2021-02-05 15:27 UTC, mehradans92 commented on htf/utils.py
>          new_cg_mat = np.where(CG_matrix == 0, CG_matrix, 1)
Shouldn't the condition be?
```CG_matrix != 0```

2021-02-05 16:09 UTC, geemi725 commented on htf/utils.py
>          new_cg_mat = np.where(CG_matrix == 0, CG_matrix, 1)
This will give 0's in places where CG_matrix is 0 and 1's where CG_matrix !=0

2021-02-05 16:11 UTC, geemi725 commented on htf/utils.py
>          new_cg_mat = np.where(CG_matrix == 0, CG_matrix, 1)
I'll add a different variable name. Need both mass weighted and non-mass weighted in some cases. For example when you want to compute forces and positions. That's why I added the second return statement. Thoughts?

2021-02-05 16:59 UTC, mehradans92 commented on htf/utils.py
>          new_cg_mat = np.where(CG_matrix == 0, CG_matrix, 1)
I see. Maybe you can call the option `mass_weighted=True` and try:
`
if mass_weighted:
      return CG_matrix
else:
      return np.where(CG_matrix == 0, CG_matrix, 1)
`

2021-02-05 17:02 UTC, mehradans92 commented on htf/utils.py
>          new_cg_mat = np.where(CG_matrix == 0, CG_matrix, 1)
Make sure you `pull` from master again. My new PR (#269 ) just got merged and there were some changes in the variable names.

2021-02-08 14:08 UTC, mehradans92 commented on htf/utils.py
> +    :param mapping_operator: List of lists of beads distribution. Note that each list should
To keep it consistent with other part of the code, please use `mapping operators` or `beads mapping` instead of `beads distribution`

2021-02-08 14:15 UTC, mehradans92 requested changes

2021-02-08 14:15 UTC, mehradans92 commented on examples/07.  Molecules CG Mapping.ipynb
> +    "mapping_FF = htf.matrix_mapping(protein_FF,Beads_distribution,mass_weighted=True)\n",
Since the default argument  for `mass_weighted` is `True` in `htf.matrix_mapping`, I think we don't need to set it to `True` again here. Does it not work without it?

2021-02-08 15:18 UTC, geemi725 commented on examples/07.  Molecules CG Mapping.ipynb
> +    "mapping_FF = htf.matrix_mapping(protein_FF,Beads_distribution,mass_weighted=True)\n",
It does, but I added it here so that a user would know there is a flag to get a non-mass weighted matrix as well. But it wouldn't make a big difference with or without it in my opinion.

2021-02-08 15:44 UTC, mehradans92 approved these changes

2021-02-09 04:42 UTC, merged