Molecular features- multiple molecules
ur-whitelab/hoomd-tf pull request #309
Opened 2021-03-12 16:49 UTC by geemi725

Addresses issue #308

2021-03-16 16:49 UTC, whitead requested changes
Can you add a unit test? Doesn't need to check anything, just make sure it runs the code.

2021-03-16 16:49 UTC, whitead commented on htf/utils.py
> +    :type bnd_indices: numpy array
Can you specify the type (int, float) and can it be list or must it be an array?

2021-03-16 16:57 UTC, geemi725 commented on htf/utils.py
> +    :type bnd_indices: numpy array
They need to be arrays. For some reason didn't work with lists initially. I will add the datatype to the documentation.

2021-03-17 21:02 UTC, pep8speaks commented
Hello @geemi725! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`htf/test-py/test_utils.py`](https://github.com/ur-whitelab/hoomd-tf/blob/221722d000c0869cb974bca6cad789600b7bfd84/htf/test-py/test_utils.py):

> [Line 580:17](https://github.com/ur-whitelab/hoomd-tf/blob/221722d000c0869cb974bca6cad789600b7bfd84/htf/test-py/test_utils.py#L580): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 580:21](https://github.com/ur-whitelab/hoomd-tf/blob/221722d000c0869cb974bca6cad789600b7bfd84/htf/test-py/test_utils.py#L580): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 580:26](https://github.com/ur-whitelab/hoomd-tf/blob/221722d000c0869cb974bca6cad789600b7bfd84/htf/test-py/test_utils.py#L580): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 585:14](https://github.com/ur-whitelab/hoomd-tf/blob/221722d000c0869cb974bca6cad789600b7bfd84/htf/test-py/test_utils.py#L585): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 585:20](https://github.com/ur-whitelab/hoomd-tf/blob/221722d000c0869cb974bca6cad789600b7bfd84/htf/test-py/test_utils.py#L585): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 585:28](https://github.com/ur-whitelab/hoomd-tf/blob/221722d000c0869cb974bca6cad789600b7bfd84/htf/test-py/test_utils.py#L585): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 585:64](https://github.com/ur-whitelab/hoomd-tf/blob/221722d000c0869cb974bca6cad789600b7bfd84/htf/test-py/test_utils.py#L585): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 585:68](https://github.com/ur-whitelab/hoomd-tf/blob/221722d000c0869cb974bca6cad789600b7bfd84/htf/test-py/test_utils.py#L585): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 585:73](https://github.com/ur-whitelab/hoomd-tf/blob/221722d000c0869cb974bca6cad789600b7bfd84/htf/test-py/test_utils.py#L585): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 585:75](https://github.com/ur-whitelab/hoomd-tf/blob/221722d000c0869cb974bca6cad789600b7bfd84/htf/test-py/test_utils.py#L585): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 588:35](https://github.com/ur-whitelab/hoomd-tf/blob/221722d000c0869cb974bca6cad789600b7bfd84/htf/test-py/test_utils.py#L588): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 589:1](https://github.com/ur-whitelab/hoomd-tf/blob/221722d000c0869cb974bca6cad789600b7bfd84/htf/test-py/test_utils.py#L589): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2021-03-17 23:50 UTC, whitead approved these changes

2021-03-18 16:07 UTC, merged